name = "mcp-memory-remote"
main = "src/index.ts"
compatibility_date = "2024-12-01"
minify = true

# Account configuration
account_id = "1a481f7cdb7027c30174a692c89cbda1"

[env.production]
name = "mcp-memory-remote-prod"

[env.staging]
name = "mcp-memory-remote-staging"

# D1 Database for knowledge graph
[[d1_databases]]
binding = "DB"
database_name = "knowledge-graph"
database_id = "480a939e-6989-4d45-855f-ee1e9131ae88"

# KV Namespaces for caching
[[kv_namespaces]]
binding = "ENTITY_CACHE"
id = "77befdab14f64cdfa573a8f0bc2c30d8"

[[kv_namespaces]]
binding = "SEARCH_INDEX"
id = "0c70c0a7469e45928ca9d2bb708d82e4"

# Variables
[vars]
MEMORY_VERSION = "1.0.0"
MAX_ENTITIES = "10000"
MAX_RELATIONS = "50000"
CACHE_TTL = "3600"
